# Generated by Django 5.1.2 on 2024-10-19 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_bloggerprofilemodel_viewersprofilemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bio', models.TextField(null=True)),
                ('Category', models.CharField(choices=[('Technology', 'Technology'), ('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('Politics', 'Politics'), ('Business', 'Business'), ('Health', 'Health'), ('Education', 'Education'), ('Travel', 'Travel'), ('Food', 'Food'), ('Fashion', 'Fashion')], max_length=100, null=True)),
                ('Blog_Pic', models.ImageField(null=True, upload_to='Media/Blog_Pic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
