# Generated by Django 5.1.2 on 2024-10-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_blogpostmodel_created_blogpostmodel_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodel',
            name='BlogTitle',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
