# Generated by Django 5.1.2 on 2024-10-19 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_alter_blogpostmodel_blogtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
